### ISSUE TITLE
Assert Equal XML is calling assert-equal() incorrectly

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#107]
Looking at the below lines of code the first argument being passed to assert-equal seems to be the message, when it should be the last argument passed to assert-equal:

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L584

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L585

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L589

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L590

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L601

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L602

The fix should include automated tests that use `test:assert-throws-error-with-message` 
to make sure each of the above failure messages read correctly when the error is thrown.

**Comment by rjrudin** [comment]
These all look to be fixed in the latest version of test-helper.xqy.
