### ISSUE TITLE
Use fail() instead of calling assert-true with a false value

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#108]
Replace references in the code that call `assert-true` where the value is `fn:false()`, if the idea is to cause the test to fail, we should instead use the `fail` function. 

Here are some examples that should be replaced:
https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L581

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L595

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L598

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L605

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L607

The fix should include tests that call `assert-throws-error-with-message` to ensure the above conditions continue to return the expected failure message.

**Comment by rjrudin** [comment]
DEVEXP-550.
