### ISSUE TITLE
Rename to assert-greater-than-or-equal() and assert-less-than-or-equal()

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#109]
Rename `assert-meets-minimum-threshold()` to `assert-greater-than-or-equal()`:

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L757

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L761

Rename `assert-meets-maximum-threshold()` to `assert-less-than-or-equal()`:

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L777

https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L781

Keep the old method signature around for backwards compatibility, but add a comment marking it as deprecated.  Maybe even add an info-level log statement when the old method signature is used letting them know this method is deprecated and will go away in a future release.

**Comment by dmcassel** [comment]
Changing names of assert functions is a breaking change, so I propose that (based on semantic versioning) this triggers a major version number bump.

**Comment by jamesagardner** [comment]
For the time being the existing functions were left in place, but a warning will be logged for using them.  At some point in the future, when those functions are removed, we'll increase the major version number.
