### ISSUE TITLE
Setup real JUnit tests for marklogic-unit-test-modules

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/marklogic-unit-test#11]
We have a test app that can be deployed on port 8090 locally already. And there are a few tests in place. Just need to expand this so that it's easy to write tests for new features, such as the PR that's open right now for supporting additional formats for test output. 

Can use ml-junit for writing these tests.

**Comment by jamesagardner** [comment]
@rjrudin would you say this is complete now that marklogic-junit is included in version 1.0.beta?
