### ISSUE TITLE
test.assertTrue(null) = success

### ISSUE THREAD

**Issue by aclavio** [marklogic-community/marklogic-unit-test#112]
The `assert-true` function reports success when passed a null, undefined, or empty sequence (xqy).
This feels particularly egregious in SJS as it doesn't adhere to javascripts concept of "truthiness".

```xquery
(: xqy :)
test:assert-true(())
```
```javascript
// sjs
test.assertTrue(null);
test.assertTrue(undefined);
````

**Comment by jamesagardner** [comment]
I wonder if it makes sense to introduce a `/test/testHelper.sjs` implementation that either wraps the existing XQuery assertion functions or has JavaScript implementations that better match with JavaScript idioms.

**Comment by rjrudin** [comment]
Will see if we can do something useful in 1.4 for this - starting with the 3 scenarios in the original ticket.

**Comment by dmcassel** [comment]
> I wonder if it makes sense to introduce a /test/testHelper.sjs implementation that either wraps the existing XQuery assertion functions or has JavaScript implementations that better match with JavaScript idioms.

I'm in favor of a `testHelper.sjs` that works with JS idioms. I've run into some challenges with parameters getting passed between languages (discussed in [PR155](https://github.com/marklogic-community/marklogic-unit-test/pull/155/files/e9a38526ac30e03ad1a72b6b4afc90a180f2bf53#diff-1b331779edb0565851451d91be7708efd478fe90711871aca33d954dd9f54dda))

**Comment by rjrudin** [comment]
DEVEXP-552

**Comment by rjrudin** [comment]
Will be in 1.4.0.
