### ISSUE TITLE
Documentation on mlGenerateUnitTestSuite

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/marklogic-unit-test#113]
Add a callout to `gradle help --task mlGenerateUnitTestSuite` on the README or show the parameters to mlGenerateUnitTestSuite.

Documentation in code:
https://github.com/marklogic-community/ml-gradle/blob/e15f90aba0c9507481ae99caaab6452336bcde27/src/main/groovy/com/marklogic/gradle/MarkLogicPlugin.groovy#L309

**Comment by jamesagardner** [comment]
This should be done after #82.  Could be tackled at the same time #100 is being worked.

**Comment by prestonmcgowan** [comment]
Added to commit with #114
