### ISSUE TITLE
Order the tests displayed to be in the order they will be executed.

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/marklogic-unit-test#116]
The UI should display all the files being run for a test.
The UI should display the:
* setup files first
* tests alphabetically sorted
* teardown files last

This screen capture shows the current display
![image](https://user-images.githubusercontent.com/1315891/66515982-163fcd80-eaae-11e9-8b04-d3b1fa0e5ce0.png)

**Comment by jamesagardner** [comment]
markogic-unit test isn't treating `suite-setup.sjs` and `suite-teardown.sjs` as setup/teardown modules.  It's treating those as separate tests to be executed.  I think you want `suiteSetup.sjs` and `suiteTeardown.sjs` instead.

Here is the place in the code where reserved file names are specified: https://github.com/marklogic-community/marklogic-unit-test/blob/63a8aa4a36d1d2576469a8972ec91960b204a980/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-controller.xqy#L31

**Comment by prestonmcgowan** [comment]
That looks like it fixed it.

Are those files for SJS going to be autogenerated?
https://github.com/marklogic-community/ml-gradle/issues/511

**Comment by jamesagardner** [comment]
I don't see why they couldn't be auto-generated when marklogic-community/ml-gradle#511 is implemented.
