### ISSUE TITLE
Testing with SJS Sample Code throws errors

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/marklogic-unit-test#117]
https://marklogic-community.github.io/marklogic-unit-test/docs/testing-with-sjs/

```
[javascript] JS-JAVASCRIPT: let actual = fib.getFibbed(3, 3); -- Error running JavaScript request: SyntaxError: Identifier 'actual' has already been declared
Stack Trace
At line 20 column 4:
In let actual = fib.getFibbed(3, 3);

18. // Scenario 2: start later in the sequence
19.
20. let actual = fib.getFibbed(3, 3);
21.
22. assertions.push(
```

The sample code provided in documentation should execute without needing to be debugged.

**Comment by prestonmcgowan** [comment]
Additionally, the next failure would have been locating the fibonacci.sjs file. 
Where can this file be located?

**Comment by hansenmc** [comment]
Seems like if the variable `actual` variable is going to be re-used, the second code block should leave out the `let` and just set a new value, or both of those declarations should use `var` instead of `let`.
