### ISSUE TITLE
Upgrade Java Client and other dependencies

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/marklogic-unit-test#129]
Both marklogic-junit5 and marklogic-unit-test-client are using 4.x of the Java Client; 5.4.0 is now available. 

Should also bump up all dependencies in marklogic-junit5 to latest versions. 

It appears that the DHF dependency can be removed - it's compileOnly, but I don't see it being used anywhere.

**Comment by venuiyengar** [comment]
I removed compileOnly dependency for DHF. However, in order to compile I needed to add the following:
	api "com.fasterxml.jackson.core:jackson-databind:2.12.2"
	api "org.slf4j:slf4j-api:1.7.30"

I guess this should be OK!
I also bumped versions for other dependencies
marklogic-junit5 tests runs without any issues

**Comment by rjrudin** [comment]
That's correct - Java Client 5.4 switched to Gradle's api/implementation configurations, which means not every dependency comes over automatically (which is intentional). 

Check the version number of Jackson that Java Client 5.4 is using though - I think it's 2.11.1, in which case you should use jackson-databind 2.11.1

You can run "gradle dependencies" to see all the dependencies and verify you don't have a mismatch of version numbers.
