### ISSUE TITLE
Use recommended Gradle configurations instead of deprecated ones

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/marklogic-unit-test#130]
marklogic-unit-test-client and marklogic-junit5 should both starting using the java-library plugin and api/implementation instead of compile/runtime.

See https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle for more info. 

Here's an example of a project switching to the new configurations - https://github.com/marklogic-community/ml-javaclient-util/commit/1c53cbc5e5bd5cfa702bdcd91d4e51d6d8fb7986

**Comment by venuiyengar** [comment]
Changed build.gradle to start using java-library plugin and changed dependencies to use api/implementation for both marklogic-unit-test-client ant marklogic-junit5
