### ISSUE TITLE
DeployOtherServersCommand.java missing from DataHub 5.x

### ISSUE THREAD

**Issue by laquereric** [marklogic-community/marklogic-unit-test#140]
One file was removed between DataHub between 4.x and 5.x**:

**marklogic-data-hub\marklogic-data-hub\src\main\java\com\marklogic\hub\deploy\commands\DeployOtherServersCommand.java 
. 
This breaks the suggested build.gradle script.

import com.marklogic.hub.deploy.commands.DeployHubOtherServersCommand not found.

**Comment by hansenmc** [comment]
Isn't that a DataHub issue, not an ml-unit-test issue? Why would ml-unit-test have references to DataHub classes? Do you know where that might be?

**Comment by rjrudin** [comment]
I believe this is referring to a gist for creating test resources in a DHF 4 application - possibly this - https://gist.github.com/rjrudin/df0ff09f5bff67833048e67f1ebaa5d6

This gist is then for a DHF 5 application - https://gist.github.com/rjrudin/0dd97eaee16b1f8dc75a35c7acf7b4e1

However, neither of those are supported by DHF. I recommend instead following the guidance in this DHF example project for testing a DHF application - https://github.com/marklogic/marklogic-data-hub/tree/master/examples/reference-entity-model#testing-support 

Closing this as the gists don't pertain to marklogic-unit-test.
