### ISSUE TITLE
Document out of date

### ISSUE THREAD

**Issue by DavidEnnis-17llamas** [marklogic-community/marklogic-unit-test#147]
https://marklogic-community.github.io/marklogic-unit-test/include/

this page refers to a beta version of ml-unit test

**Comment by rjrudin** [comment]
Thanks @DavidEnnis-17llamas for reporting this, will fix soon.

**Comment by rjrudin** [comment]
Will address soon, but change is to the gh-pages branch so does not need to be tied to a release

**Comment by rjrudin** [comment]
Page has been updated - https://marklogic-community.github.io/marklogic-unit-test/include/
