### ISSUE TITLE
Enable providing custom code coverage module

### ISSUE THREAD

**Issue by peetkes** [marklogic-community/marklogic-unit-test#168]
It would be nice if ml-unittest provided away to provide a custom code coverage module. It has to adhere to the outcome of the provided code coverage module.
So by providing an extra property eg. 'ml-unittest-code-coverage-module=/my/own/codecoverage.xqy one would be able to select the custom code coverage module

**Comment by rjrudin** [comment]
Do you have an example of one in mind?

**Comment by rjrudin** [comment]
Going to close this as we don't have any plans to do this in the 1.x timeframe, but feel free to keep a conversation going here.
