### ISSUE TITLE
dead link in docs

### ISSUE THREAD

**Issue by DavidEnnis-17llamas** [marklogic-community/marklogic-unit-test#201]
https://marklogic-community.github.io/marklogic-unit-test/

Please refer to the middle of the page:

Please see the [Getting started guide](https://marklogic-community.github.io/docs) to learn how to include marklogic-unit-test in your project and to start writing and running tests.

That link is dead.

**Comment by rjrudin** [comment]
Thanks @DavidEnnis-17llamas  - links should all be fixed now. Unfortunately we ran into an issue where nice-looking permalinks work fine locally - this is using GitHub's support for Jekyll - but they don't always seem to work when deployed via GitHub.

**Comment by DavidEnnis-17llamas** [comment]
Perfect. Works. Cleaning up the web one 404 at a time.
