### ISSUE TITLE
Wiki Page is empty

### ISSUE THREAD

**Issue by DavidEnnis-17llamas** [marklogic-community/marklogic-unit-test#202]
Thanks to the recent (And valuable) updates to may MarkLogic documentation sources online, marklogic-unit-test has wonderful documentation.  However, if One were to go to the repository and then click on the "Wiki" tab at the top, they would be left with little to go on:

https://github.com/marklogic-community/marklogic-unit-test/wiki

Suggest that this page be disabled (if GitHub allows that) or a link be added to the full documentation.

**Comment by rjrudin** [comment]
Thanks and a good idea - the content there was all old, so disabled the feature.
