### ISSUE TITLE
Support Testing of the MarkLogic Data Hub Framework (DHF)

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-unit-test#26]
Support running input flows, harmonization flows, and doing other hub-related things. 

Some natural things to test include
- ingest data to an input flow and check the results, including
   - the envelope created with header metadata
   - any transforms to content
   - REST services on top of the raw data (not that common, but can be done)
   - SQL or SPARQL views projected via TDE
   - traces for errors created, or other error reports and audits
   - ingest a batch or single real-time item
- harmonize data and check
   - the same items above

**Comment by dmcassel** [comment]
Probably a new component.

**Comment by rjrudin** [comment]
For reference, here's a project that shows a DHF4 project with marklogic-unit-test being used - https://github.com/rjrudin/marklogic-junit/tree/master/examples/simple-dhf4 

A lot here depends on the scope of "unit testing" for a team. On a current project, we're using marklogic-unit-test for testing a bunch of SJS code, but nothing that involves any interaction with a database. But if marklogic-unit-test is used for code that does perform transactions with the database, then you really ought to have a parallel setup of staging and final databases / app servers. My recommendation is not to use marklogic-unit-test for that kind of testing, but rather do system-level testing of ML endpoints via a testing framework outside of ML (e.g. JUnit5 for a Java team).

**Comment by josvr** [comment]
I agree with Damon Feldman @damonfeldman here. @rjrudin a default unit test framework setup should be automatically put into place if you run create a new DHF project with support of the tools listed by Damon Feldman. Please forward this to Product Management. Unit test/integration testing is nowadays so important, that it should be by default part of the product.

**Comment by jamesagardner** [comment]
Closing this out as it's being tracked in the DHF project at https://github.com/marklogic/marklogic-data-hub/issues/2125
