### ISSUE TITLE
Add documentation for developing and testing ml-unit-test locally

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/marklogic-unit-test#29]
Describe how to deploy the project in ./ml-unit-test-client and hack around with it.

**Comment by dmcassel** [comment]
I mentioned this in the CONTRIBUTING.md file that's in my current PR.

**Comment by dmcassel** [comment]
@rjrudin is this addressed satisfactorily [here](https://github.com/marklogic-community/ml-unit-test/blob/develop/CONTRIBUTING.md#test-your-code)?

**Comment by rhdunn** [comment]
Some comments/feedback:

1. The documentation should refer to running `./gradlew` not `gradle`, as `gradle` may not be on the path, and the project has committed a functioning gradle wrapper.
1. The `gradle mlDeploy` command will fail with the error `Local message: failed to apply resource at eval: Unauthorized. Server Message: Unauthorized` -- you need to edit `marklogic-unit-test-client/gradle.properties` and change mlPassword.

NOTE: I have not been able to set this using `./gradlew -DmlPassword=...`, via `GRADLE_OPTS`, or similar. It would be useful if these were overrideable outside `gradle.properties`.

**Comment by jamesagardner** [comment]
Updated the Wiki page to reference https://github.com/marklogic-community/marklogic-unit-test/blob/master/CONTRIBUTING.md.  This should be satisfactory for now.  Additional instructions can be captured as new issues.
