### ISSUE TITLE
Allow substitutions during deployment

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/marklogic-unit-test#32]
In order to test a REST extension, I need a username and password. Rather than including those in the code, I'd like to have a module deployed with the test modules that has constants I can use. Those constants would have values that are overwritten during deployment with configurable values. For instance, I could have a module that includes:

    declare variable $TEST-USERNAME := "%%TEST-USERNAME%%";
    declare variable $TEST-PASSWORD := "%%TEST-PASSWORD%%";

and a properties file that includes:

    TEST-USERNAME=admin
    TEST-PASSWORD=admin

Then my unit tests can include the library module and use those constants. (Maybe this is already possible, but I don't see such a module.)

**Comment by hansenmc** [comment]
Although we still might want to perform integration tests that make actual HTTP requests to test a custom REST endpoint, it is possible to test custom REST endpoint modules without making HTTP requests.

With a [custom REST extension "example"](https://docs.marklogic.com/guide/rest-dev/extensions#id_75293), the module is installed at:
`/marklogic.rest.resource/example/assets/resource.xqy`

A test could import the module and test it's methods like you would any other module, without making an HTTP request:

    import module namespace test="http://marklogic.com/roxy/test-helper" at "/test/test-helper.xqy";
    import module namespace example = "http://marklogic.com/rest-api/resource/example" at 
      "/marklogic.rest.resource/example/assets/resource.xqy";
    
    test:assert-equal(2, count(example:get(map:map(), map:entry("arg1", ("bar", "baz")) )/args/arg1) ),
    test:assert-empty(example:get(map:map(), map:map())/args/arg1)

**Comment by dmcassel** [comment]
Good point. I wanted to verify that the parameters were interpreted correctly, but as you demonstrate, I can set up the $params map myself.

**Comment by rjrudin** [comment]
I did a quick test to verify that this works - was using ml-gradle 3.7.1 (as that's what the test project in marklogic-unit-test-client is currently using on the master branch), and I added the following to a test module:

    (: Host is %%mlHost%% :)

And it was replaced with "localhost" correctly. So I believe this is supported properly.
