### ISSUE TITLE
Document how to include marklogic-unit-test and set up for a Data Hub

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-unit-test#36]
Set up a wiki page or similar that describes how to link marklogic-unit-test to a Data Hub build, where to put tests etc.

Data Hub uses a slightly altered/extended version of ml-gradle, so downloading a component from a maven repository and altering the modules paths needs some explanation.

**Comment by kosed** [comment]
see https://github.com/marklogic/marklogic-data-hub/issues/1300 for a tentative option.

**Comment by popzip** [comment]
I'm assuming this is not sufficient? https://github.com/marklogic-community/ml-unit-test/wiki/Integrating-with-DHF But might be the place for additional info?

**Comment by rjrudin** [comment]
I think there's also the need for https://gist.github.com/rjrudin/ce347cd657b3768332c17641fdb12907 - but that part is not specific to ml-unit-test. That part assumes you want a test server/database that mirrors either your staging server/db or final server/db (I think most likely the latter). 

I think the DHF project should have instructions on how to setup test resources. ml-unit-test can then have docs on - hey, if you have test resources, here's how to use ml-unit-test to run tests against them.

**Comment by popzip** [comment]
@rjrudin I think I understand that. You're suggesting that DHF explain that databases need to be set up for testing. Then developer uses ml-unit-test to run on the test databases? 

If that's the case, feel free to make a PR with that level of info to DHF, or capture in a ticket in response (new or in response to an existing Q).

**Comment by jamesagardner** [comment]
I'm thinking about closing this issue.  I believe DHF already has some example automated tests and @rjrudin is doing some work to bring marklogic-unit-test 1.0.beta into the mix.

Thoughts?

**Comment by jamesagardner** [comment]
Closing this issue for the same reasons #65 was closed.  I believe this is better tracked in the DHF project, and work has already been started there.
