### ISSUE TITLE
assert-equal-json no longer reports the location of comparison differences

### ISSUE THREAD

**Issue by rhdunn** [marklogic-community/marklogic-unit-test#37]
When you have large values that are being compared for equality, it can be difficult to identify the location of the error when looking at two large blocks of text.

The original assert-equal-json implementation provided the paths to the expected and actual nodes being compared. This made it easier to locate the source of the errror.

Ideally, it would be useful if the differences were marked up like in a diff output and properly formatted so you could see what the error is, what the expected value is, and what the actual value is.

**Comment by dmcassel** [comment]
@rhdunn https://github.com/marklogic-community/ml-unit-test/pull/35 includes some improvements in comparing JSON, but needs a PR review. Are you available to take a look at it?

**Comment by jamesagardner** [comment]
Closing this out as #35 was merged in.  @rhdunn et me know if this needs to be re-opened.
