### ISSUE TITLE
Support Nested Test Suites

### ISSUE THREAD

**Issue by lukasz1234567890** [marklogic-community/marklogic-unit-test#45]
When you create a test suite that is nested to, for example, mirror your modules folder structure, the suites are not discovered. Only immediate child folders of `/test/suites' are found.

To reproduce create test suite under `/test/suites/root/my-suite/`.

I think I've found the problematic code [here](https://github.com/marklogic-community/marklogic-unit-test/blob/571fb298103592b49be098c38610d3adad615f37/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-controller.xqy#L56) `and fn:not(fn:contains($path, "/"))`. Don't know what was the motivation for this requirement.

**Comment by dmcassel** [comment]
The convention is that all code files in `/test/suites/&lt;my-suite&gt;/` are assumed to be tests; anything outside of there is assumed not to be. This allows, for instance, for having `test-data` and `lib` directories under the test suites. See [this Smart Mastering test suite for an example](https://github.com/marklogic-community/smart-mastering-core/tree/master/src/test/ml-modules/root/test/suites/merging-json). 

While I get the appeal of what you're proposing, we'd need to change the identification of tests in a way that would break a lot of existing test code. This could be done with annotations, for instance, but current users would need to apply those annotations to existing code. I'd be interested in hearing from others about the value of more flexible test paths versus the need to apply those annotations (or whatever got settled on).

**Comment by damonfeldman** [comment]
I spoke with the team about this, and it's a good use case, to package up functionality with other modules, and have more levels of nesting.
