### ISSUE TITLE
Add Failure Message to Assert Functions

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#51]
Update all assert functions so that they accept an optional message argument.  The argument should be a string.  This message should be displayed whenever a test fails due to an assertion failure.  The intention of this message is to provide a description that gives context around why a test exists and what it is attempting to test.  This type of failure message can be very valuable in quickly diagnosing and addressing regression test failures.

**Comment by jamesagardner** [comment]
`assert-true` and `assert-false` both had their method signature changed, the message argument is now the first argument to be consistent with other testing libraries like JUnit.  This needs to be called out in the documentation.

Some of the assertion methods had their default failure messages change.  Though the failure names shouldn't have changed.

**Comment by dmcassel** [comment]
sounds like thevery major version number needs to change when L this is released

**Comment by jamesagardner** [comment]
@dmcassel definitely.  I'm targeting the 1.0 release, which will have a handful of breaking changes between this and #52 I suspect most projects will need to be updated.
