### ISSUE TITLE
Remove Roxy from Namespaces

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#52]
The following namespaces are in use as of this issue being created today:
- `http://marklogic.com/roxy/test`
- `http://marklogic.com/roxy/test-helper`
- `http://marklogic.com/roxy/test-coverage`

**Comment by jamesagardner** [comment]
Updating the namespace will break existing tests built on the old namespace of `http://marklogic.com/roxy/test-helper`.  I believe we should make this change before we're permanently attached to the roxy name as part of the 1.0 release.

I'd like to consolidate all libraries and data on the following namespace `http://marklogic.com/unit-test`.

I could possibly see a reason to keep the test-coverage in a separate namespace, as they could take a life of its own, but I'm not convinced of that just yet.

**Comment by rjrudin** [comment]
Sounds good to me. It's just something that will go into the release notes for the next version with the change in it.

**Comment by dmcassel** [comment]
kids today, no appreciation for history. jk, sounds good. should roll the major version number when this change gets released.

**Comment by jamesagardner** [comment]
I think I'm favoring `http://marklogic.com/test/unit`  I'm going to use that for now unless there's good objection not to.

**Comment by rjrudin** [comment]
Sounds good to me.

**Comment by jamesagardner** [comment]
After internal discussion, going to update the namespace again on the develop branch to become `http://marklogic.com/test`

**Comment by jamesagardner** [comment]
Anyone migrating from a pre 1.0 version of marklogic-unit-test will need to do a global find and replace in their editor of choice and replace the following references:
- `http://marklogic.com/roxy/test` replace with `http://marklogic.com/test`
- `http://marklogic.com/roxy/test-helper` replace with `http://marklogic.com/test`
- `http://marklogic.com/roxy/test-coverage` replace with `http://marklogic.com/test/coverage`
