### ISSUE TITLE
sec:remove-credential is not supported on MarkLogic 8

### ISSUE THREAD

**Issue by rhdunn** [marklogic-community/marklogic-unit-test#57]
Running `./gradlew mlDeploy` on MarkLogic 8 gives the error:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Git\marklogic-unit-test\marklogic-unit-test-client\build.gradle' line: 103

* What went wrong:
A problem occurred evaluating project ':marklogic-unit-test-client'.
> Local message: failed to apply resource at eval: Internal Server Error. Server Message: XDMP-UNDFUN: (err:XPST0017) Undefined function sec:remove-credential()
```

`sec:remove-credential` was introduced in MarkLogic 9.

**Comment by jamesagardner** [comment]
@rhdunn I think this issue has more to do with [ml-gradle](https://github.com/marklogic-community/ml-gradle).  I'm not sure that MarkLogic 8 support in newer versions ml-gradle or marklogic-unit-test is a high priority as [MarkLogic 8 is reaching it's end of life on Nov 13, 2019](https://help.marklogic.com/).

Going to close the issue as won't fix.
