### ISSUE TITLE
Difficult to run a unit test in qconsole

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-unit-test#62]
### Workaround:
*  Isolate all the setup to the setupSuite.sjs (or xqy) module 
   * That is - do not call load-test-module() and related functions directly from the test
*  Spawn the setup module so the path is correct at runtime: 
    * xdmp.spawn("/test/suites/Looping/suiteSetup.sjs")

### Issue:

If a test uses any of the load-test-data helper functions, then they won't run in qconsole. This is because load-test-data uses the caller's module URI to figure out where to get the test data in the modules DB and when running from qconsole the calling module is the qconsole module.

It's a huge benefit to use tests as starting points for one's own work, and as guaranteed-working sample code, so it would be better if we can generally paste a test into qconsole and go. (perhaps adding "suiteSetup.sjs" in another buffer and running that first).

A possible fix is to add an override function to set the test data directory explicitly, rather than deriving it from the calling code's location. For .sjs this is more difficult, because it does not look like "static" module variables persist across eval() calls from javascript to xquery.

**Comment by jamesagardner** [comment]
I created #63 to identify the lack of documentation on successful patterns for iterating over a test or isolating a test failure.

I'm not sure we'd want to support running unit tests in QConsole.  While it may work today, as we build a richer testing runtime it may become complicated to support multiple execution patterns.

**Comment by jamesagardner** [comment]
After internal discussions I don't believe we will take actions to run automated tests directly form qconsole at this time.
