### ISSUE TITLE
Test Resource Deployment fails when entity-config present

### ISSUE THREAD

**Issue by joecrean** [marklogic-community/marklogic-unit-test#67]
There seems to be an issue when deploying a test database when there is a db json file present under `entity-config`.  In my testing I have an entity and when I try to deploy test resources it does not create the TEST db and the step afterwards to create the app server errors off with http 400 because the db doesn't exist. If I rename the db json file under `entity-config` then it all works fine. So I guess there is a bigger issue - when we create the test db we need to search all three possible locations hub-internal-config, entity-config and ml-config and merge the three just like in mlDeploy... looks to me like the DeployHubDatabaseCommand cannot deal with 3 locations. This is tested against a development version of `marklogic-unit-test-modules` - `0.13.develop` -  built locally. I can also provoke this error in the `simple-dhf4` example by adding a db json file under `entity-config`. 

More details on this: 
Here is the output of my deployment of test resources (the test db is STAGING).
```
Deploying a test database with name data-hub-STAGING-TEST based on configuration file named staging-database.json
Checking for existence of resource: data-hub-STAGING
Sending XML GET request as user 'admin' to path: /manage/v2/databases
Found database with name of data-hub-STAGING, so updating at path /manage/v2/databases/data-hub-STAGING/properties
Sending JSON PUT request as user 'admin' to path: /manage/v2/databases/data-hub-STAGING/properties
Updated database at /manage/v2/databases/data-hub-STAGING/properties
Sending XML GET request as user 'admin' to path: /manage/v2/hosts
Finding eligible hosts for forests for database: data-hub-STAGING
Sending XML GET request as user 'admin' to path: /manage/v2/hosts
Checking for existence of resource: data-hub-STAGING
Sending XML GET request as user 'admin' to path: /manage/v2/databases
Sending XML GET request as user 'admin' to path: /manage/v2/databases/data-hub-STAGING/properties
:hubDeployTestDatabase (Thread[Task worker for ':',5,main]) completed. Took 3.232 secs.
```

In order to workaround the issue I rename the `staging-database.json` under `entity-config` and rerun the deploy of test resources.. it then runs through just fine, here is the output:
```
> Task :hubDeployTestDatabase
Task ':hubDeployTestDatabase' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Deploying a test database with name data-hub-STAGING-TEST based on configuration file named staging-database.json
Checking for existence of resource: data-hub-STAGING-TEST
Sending XML GET request as user 'admin' to path: /manage/v2/databases
Creating database: data-hub-STAGING-TEST
Sending JSON POST request as user 'admin' to path: /manage/v2/databases
Created database: data-hub-STAGING-TEST
Sending XML GET request as user 'admin' to path: /manage/v2/hosts
Finding eligible hosts for forests for database: data-hub-STAGING-TEST
Sending XML GET request as user 'admin' to path: /manage/v2/hosts
Checking for existence of resource: data-hub-STAGING-TEST
Sending XML GET request as user 'admin' to path: /manage/v2/databases
Sending XML GET request as user 'admin' to path: /manage/v2/databases/data-hub-STAGING-TEST/properties
Checking for existence of resource: data-hub-STAGING-TEST-1
Sending XML GET request as user 'admin' to path: /manage/v2/forests
Creating forest: data-hub-STAGING-TEST-1
Sending JSON POST request as user 'admin' to path: /manage/v2/forests
Created forest: data-hub-STAGING-TEST-1
:hubDeployTestDatabase (Thread[Task worker for ':',5,main]) completed. Took 5.648 secs.
:hubDeployTestServer (Thread[Task worker for ':',5,main]) started.
```

**Comment by jamesagardner** [comment]
@joecrean this sounds like an issue better suited for the DHF project.  I suspect the root cause is more related to the DHF project structure, and the DHF code used to deploy and manage a datahub.  Would you mind filing an issue there and linking it here?

If it turns out that the solution requires an adjustment in this project I'll re-open this issue with the details necessary to make it all work together.
