### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by jmakeig** [marklogic-community/marklogic-unit-test#71]
After reading the docs site I still have no idea how to get started. I copied the `ml-gradle/examples/unit-test-project` directory, upgraded to Gradle 5, and updated `marklogicUnitTestVersion=1.0.beta` in `gradle.properties`. However, when I do a `gradle build` I get:

```
* Where:
Build file '/Users/jmakeig/Workspaces/test-yo/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'test-yo'.
> Could not find method mlBundle() for arguments [com.marklogic:marklogic-unit-test-modules:1.0.beta] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

I have no idea what I’m doing. Any help would be much appreciated.

**Comment by jamesagardner** [comment]
Hey @jmakeig,

Thanks for giving marklogic-unit-test a spin.  While our getting started documentation has room for improvement, take a look at this example ml-gradle project for the basic configuration necessary to get started: https://github.com/marklogic-community/ml-gradle/tree/master/examples/unit-test-project.

Namely the build.gradle file.  I recommend pulling down version 1.0.beta for now as that will give you the easiest path for future upgrades.

I'm hoping to get some cycles tomorrow to work on  project documentation.  If I get time I'll put together a getting started guide.

I believe @rjrudin has been using markloguc-unit-test as a part of DHF 5 development recently.  Perhaps he can give you more specific guidance for getting started on a DHF 5 project.

**Comment by jmakeig** [comment]
My [`build.gradle`](https://github.com/jmakeig/test-yo/blob/master/build.gradle) looks just like the one in the example. (But I don’t really know what I’m doing.)

```
> gradle -version

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_111 (Oracle Corporation 25.111-b14)
OS:           Mac OS X 10.14.5 x86_64
```

**Comment by jamesagardner** [comment]
@jmakeig have you had a chance to work through the getting started instructions that are now included on the [project home page](https://github.com/marklogic-community/marklogic-unit-test)?

Those instructions were inspired by this issue, and should help someone get started.  If you have the time to step through those instructions and provide feedback it would be much appreciated.

**Comment by rjrudin** [comment]
New docs have an actual "Getting Started" guide that gets you started.
