### ISSUE TITLE
Provide example of testing a DHF 5 flow

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/marklogic-unit-test#72]
I think this will ideally be done in the DHF project with a link to it from here, but I'm using this project to track this so it won't be lost in the shuffle.

**Comment by jamesagardner** [comment]
@rjrudin has a ticket been created in the https://github.com/marklogic/marklogic-data-hub/ project for this work?  I see https://github.com/marklogic/marklogic-data-hub/issues/2125, but that seems to have a DHF 4.0 label.

**Comment by rjrudin** [comment]
This is now addressed via DHF 5.5.
