### ISSUE TITLE
How to test DHF project that uses multiple databases

### ISSUE THREAD

**Issue by kosed** [marklogic-community/marklogic-unit-test#74]
### Situation:
- I have 2 dbs with different documents and configurations (especially range indexes) plus one set of modules, in the same modules db (including my tests cases)
- the dbs can be attached to separate app servers or not
- I want to run some tests exclusively against db1 and others exclusively on db2
- I can run my tests by either:
  - Running some code that will call the relevant testing APIs with parameters
  - Using the web UI provided OOTB with marklogic-unit-test
- The tests can be run against an empty db but also against a db containing an important number of indexed contextual documents that would take too much time to be loaded relatively to the actual test run time
- It is important to run the tests in a few seconds top

### More generally(out of DHF) - Tracked as issue #77 
let's consider that we have hundreds/thousand of tests (in a TDD based project) and we just want to run a few of them (current scope of changes only).

**Comment by kosed** [comment]
## My proposal includes:

### 1. Using a filter parameter that will filter the suites and or tests
  - The new nested structure introduced with 1.0.beta helps in structuring the tests and is a good start already but filtering brings more flexibility as like selecting different tests or suites in different folders (think tags and folder)
  - filters can be regex, basic substring, etc.
    - We can use a simple textbox for typing the filter, the filtered tests and or suites will then be returned after applying the filter (async ?)
  - It will be really cool for the web ui to somehow reproduce that nested structure so that unticking a suite will also untick all the descendants and vice-versa
### 2. Offering an optional application parameter (port, db, more ?) to switch on the fly or otherwise fall back to the default config (the properties offered in ml-gradle cover parts of that)
  - this is easier with api calls as the dbClient can be changed from one suite to another
  - the web ui currently does not offer any capability in this regard (switching the port might be useless though, the context db could be enough)

**Comment by eouthwaite** [comment]
+1 to this request - at the moment, my test database has indexes mimicking both the staging and final databases in a DHF4 project.
It would be useful to have marklogic-unit-test support the creation of two databases as per the data-hub and the ability to unit test groups against their corresponding database.

**Comment by jamesagardner** [comment]
The general case for this issue (selecting a subset of tests to run) is being tracked and managed with #77.

I think the DHF specific issues are being tracked and worked as a part of the DHF itself.  There are efforts under way to make it easier to perform test setup and run tests against specific sets of DHF databases.  At this point in time I don't believe marklogic-unit-test needs to make any specific set of changes to support testing DHF projects, but that DHF will need to set forth patterns and helper methods to make it easier to test DHF project code.

**Comment by jamesagardner** [comment]
I'm going to close this issue as I believe the solution lies within the DHF project.  I also believe there are several open issues that reference testing a DHF project.
