### ISSUE TITLE
Unable to run nested tests from gradle

### ISSUE THREAD

**Issue by eouthwaite** [marklogic-community/marklogic-unit-test#75]
I have a set of test suites that are all nested quite deeply based on 1.0.beta.

These work perfectly using REST and the UI, but return an error when attempting to use the gradle mlUnitTest task:

    $ ./gradlew mlUnitTest
    
    > Task :mlUnitTest
    Constructing DatabaseClient based on settings in the databaseClientConfig task property
    Run teardown scripts: true
    Run suite teardown scripts: true
    Run code coverage: false
    Running all suites...
    Done running all suites; time: 8069ms
    
    24 tests completed, 0 failed
    
    > Task :mlUnitTest FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':mlUnitTest'.
    > java.nio.file.NoSuchFileException: build/test-results/marklogic-unit-test/TEST-entities/Complaint/harmonize/ComplaintHarmonizeCsv/content.xml

No directories or files are being generated lower than `build/test-results/marklogic-unit-test/`

**Comment by eouthwaite** [comment]
As a comparison, running all the tests on 1.0.beta but in 0.x.x style (all suites directly under root/test/suites/), the results are:

    $ ./gradlew mlUnitTest
    
    > Task :mlUnitTest
    Constructing DatabaseClient based on settings in the databaseClientConfig task property
    Run teardown scripts: true
    Run suite teardown scripts: true
    Run code coverage: false
    Running all suites...
    Done running all suites; time: 5699ms
    
    
    24 tests completed, 0 failed
    
    10 test result files were written to: build/test-results/marklogic-unit-test

**Comment by lukasz1234567890** [comment]
This is still there, I hope the bug will be easy to fix. BTW, close to six months old bug in already released final 1.0.0 version.

**Comment by jamesagardner** [comment]
@lukasz1234567890 after looking further into this issue, I believe the bug resides in ml-gradle's code: https://github.com/marklogic-community/ml-gradle/blob/b92e923715fd423605aadba071461210978867c9/src/main/groovy/com/marklogic/gradle/task/test/UnitTestTask.groovy#L93

The long term plan is to move the mlUnitTest task and logic out into marklogic-unit-test, but for the time being that logic lives in ml-gradle.  I'll see if we can change those lines to support writing tests in nested directories.

**Comment by damonfeldman** [comment]
The workaround that worked for me is to create the "test-results" directory manually:

mkdir build/test-results

**Comment by lukasz1234567890** [comment]
> The workaround that worked for me is to create the "test-results" directory manually:
> 
> mkdir build/test-results

This directory is created `build/test-results/marklogic-unit-test`, it fails _deeper_, ex `java.io.FileNotFoundException: build/test-results/marklogic-unit-test/TEST-lib-tests/commons/batch-processor.xml (No such file or directory)`

**Comment by jamesagardner** [comment]
The changes were merged into ml-gradle's dev branch.  It should be included in the next release of ml-gradle.  I'm not sure what the version number will be for the next ml-gradle release.  The current release of ml-gradle is 3.16.4.

**Comment by dmcassel** [comment]
I ran into this too. It appears to only be a problem for nested reports. If I have a suite directly under test/suites, it's fine, but if I have test/suites/my-group/suite/... then I get an error. 

```
> Task :mlUnitTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlUnitTest'.
> java.io.FileNotFoundException: build\test-results\marklogic-unit-test\TEST-reports\component-lot-report.xml (The system cannot find the path specified)
```

**Comment by jamesagardner** [comment]
Has anyone tested this with ml-gradle 3.16.4 or 3.17?  Those ml-gradle versions should have the changes that address this failure.

**Comment by dmcassel** [comment]
I upgraded to 3.17 and the tests passed. Woohoo!

**Comment by grtjn** [comment]
Running into this again with ml-gradle 4.1.1. See also https://stackoverflow.com/questions/61396303/java-nio-file-nosuchfileexception-while-running-mlunittest

**Comment by grtjn** [comment]
I am actually not using nested tests, just 3 simple cases with assertEqual and assertTrue(true)
