### ISSUE TITLE
Document Using Test Data

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#76]
Reference this suite as an example: https://github.com/marklogic-community/marklogic-unit-test/tree/master/marklogic-unit-test-client/src/test/ml-modules/root/test/suites/Test%20Suites

Note that `test-data` is a reserved directories to put test specific data.

Show examples of using the `test:get-test-file("filename.txt")` function.  Note that it resolves files relative to that suites `test-data` directory.  So if called in a suite at `path/to/suite` it should load `/path/to/suite/test-data/filename.txt`.

**Comment by eouthwaite** [comment]
Is there anything useful in the testing section of the old Roxy wiki ?
https://github.com/marklogic-community/roxy/wiki/Unit-Testing

**Comment by jamesagardner** [comment]
Thanks @eouthwaite, that looks like it'd be a great start!

**Comment by dmcassel** [comment]
There's a start here: https://marklogic-community.github.io/marklogic-unit-test/docs/loading-data/

**Comment by jamesagardner** [comment]
Thanks @dmcassel

**Comment by rjrudin** [comment]
This is addressed at https://marklogic-community.github.io/marklogic-unit-test/loading-test-data.html
