### ISSUE TITLE
Unable to use suite name in test name

### ISSUE THREAD

**Issue by eouthwaite** [marklogic-community/marklogic-unit-test#79]
In [MarkLogic Workflow](https://github.com/marklogic-community/marklogicworkflow) there are a pair of tests in /test/suites/inclusive-gateway called inclusive-gateway-01.xqy and inclusive-gateway-02.xqy

They fail using 1.0.beta with the error `XDMP-MODNOTFOUND: (err:XQST0059) Module /test/suites/inclusive-gateway/-01.xqy not found` and `XDMP-MODNOTFOUND: (err:XQST0059) Module /test/suites/inclusive-gateway/-02.xqy not found`

Note I will be changing the names as they are not particularly descriptive

**Comment by jamesagardner** [comment]
I wonder if starting with a leading - in the module name is causing an issue.  If you could try to rename the -01 and -02 with a descriptive name, and try again I'd like to know if that allows the tests to run.

**Comment by eouthwaite** [comment]
Sorry, James for not being descriptive enough!

Test modules are:
 /test/suites/inclusive-gateway/inclusive-gateway-01.xqy
 /test/suites/inclusive-gateway/inclusive-gateway-02.xqy 
for some reason, "inclusive-gateway" is being removed from the module name

**Comment by jamesagardner** [comment]
I see.  That seems worth fixing.

**Comment by kghmanuel** [comment]
Similarly, if you have a folder under "suites" with the name of "lib", it will not get processed as a test suite. FYI

**Comment by jamesagardner** [comment]
@kghmanuel , the `lib/` directory is intentionally ignored by the test scanner to allow room for test-specific library modules to store code to be re-used across tests (like common test setup, or complex assertion functions) that otherwise shouldn't belong in the main source tree.
