### ISSUE TITLE
Add SJS Unit Test Example to Landing Page

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#81]
I think these are good to call out, but I'm thinking it'd be nice to show something ASAP on this page. 

For example, after briefly describing marklogic-unit-test, hop into an example. Show a bare minimum library module (in SJS), like an "echo" function. Then show what the test module looks like. Then show a screenshot of running the test module via the UI. Then show a screenshot of running the test via Intellij (will require that skeleton Java class, may not be worth mentioning that yet).

That covers the main use case - testing library functions. A secondary use case is using marklogic-junit to test endpoints. I wouldn't go into detail about that on the home page though - instead, provide a link to a Wiki page (or the README for marklogic-junit). 

I think the screenshots of the UI and the Intellij (or Eclipse) test runner will carry the most value, because it immediately shows the user how they'll be running the tests.

_Originally posted by @rjrudin in https://github.com/marklogic-community/marklogic-unit-test/pull/73_

**Comment by prestonmcgowan** [comment]
I copied sample-tests.xqy and created sample-tests.sjs

```
const test = require("/test/test-helper.xqy");

test.assertTrue(true);
test.log("sample-tests COMPLETE....");
```

**Comment by rjrudin** [comment]
I think the new docs do a much better job helping the user understand how to get going.
