### ISSUE TITLE
ML10 gradle project has error with unit test

### ISSUE THREAD

**Issue by Chunyu01** [marklogic-community/marklogic-unit-test#86]
I am having com.marklogic:marklogic-unit-test-client:1.0.beta and "com.marklogic.ml-gradle" version "3.16.0" in build.gradle of my gradle project. 
See https://github.com/marklogic-community/marklogicworkflow/issues/148
There is the following error to run unit test.
grale mlUnitTest
Execution failed for task ‘:mlUnitTest’.
Local message: failed to read resource at resources/marklogic-unit-test: Internal Server Error. Server Message: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request: reason: Extension marklogic-unit-test or a dependency does not exist: XDMP-MODNOTFOUND: (err:XQST0059) Module /marklogic.rest.resource/marklogic-unit-test/assets/resource.xqy not found . 
Can you please see whether it is the bug for ML10?

**Comment by rjrudin** [comment]
I'm assuming you ran "mlDeploy" already? 

If so, check your modules database to see if that module exists - the one that the error is reporting is missing. 

Next, what's your build.gradle file look like?

**Comment by Chunyu01** [comment]
No, There is not that /marklogic.rest.resource/marklogic-unit-test/assets/resource.xqy  in modules database.
Please see the build.gradle.
[build.gradle.zip](https://github.com/marklogic-community/marklogic-unit-test/files/3492871/build.gradle.zip)

**Comment by rjrudin** [comment]
Need to change "marklogic-unit-test-client" to "marklogic-unit-test-modules" in the "mlRestApi" dependency line. Also, should use "mlBundle" instead of "mlRestApi", as "mlRestApi" is deprecated.

**Comment by Chunyu01** [comment]
yes, that works.
