### ISSUE TITLE
Extract get-test-data-path from get-test-file

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/marklogic-unit-test#87]
get-test-file has the following logic in it:

```
fn:replace(
      fn:concat(
        cvt:basepath($test:__CALLER_FILE__), "/test-data/", $filename),
      "//", "/")
```

It can be useful to do a cts:directory-query on everything in a test data path, but building up that path requires duplicating the above code (without a "filename").

So this ticket is asking for the following function:

```
test:get-test-data-path()
```

Which will just do the following:

```
fn:replace(
    fn:concat(
      cvt:basepath($test:__CALLER_FILE__), "/test-data/"),
    "//", "/")
```

**Comment by rjrudin** [comment]
Hmm - looks like this is needed, as the test module needs to be the one that imports test-helper.xqy so that test:get-caller() returns the correct path:

```
declare function get-test-data-path($caller-path as xs:string) as xs:string
{
  fn:replace(
    fn:concat(
      cvt:basepath($caller-path), "/test-data/"),
    "//", "/")
};
```

**Comment by venuiyengar** [comment]
Is this already added to test-helper and waiting for a merge? If not I can create a pull request for this.

**Comment by grtjn** [comment]
I think I covered this in PR #139. I needed to duplicate that code as well, so it was easiest to include it there..

**Comment by rjrudin** [comment]
DEVEXP-549.

**Comment by rjrudin** [comment]
Will be in 1.4.0.
