### ISSUE TITLE
Build and Test marklogic-junit5 using Travis CI

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#91]
Travis CI appears to only be building the marklogic-unit-test-client sub-module.  We should configure Travis CI to build and test the marklogic-junit5 module with each pull request to more easily catch issues.

**Comment by jamesagardner** [comment]
This is currently preventing the tests from passing by default: https://github.com/marklogic-community/marklogic-unit-test/blob/9a1f1d91e36e6a532fd7b008e03da97f09588dc5/marklogic-junit5/gradle.properties#L4

It's probably OK to use a default password here for Travis CI purposes, then add a comment to convey the message that clients really shouldn't use default passwords.

**Comment by rjrudin** [comment]
Closing, as we'll be getting stuff setup internally with Jenkins
