### ISSUE TITLE
Build and Test MarkLogic Version 10 using Travis CI

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#92]
Configure Travis CI to build and test using MarkLogic version 10.  Preferably we'd have at least one build job for each supported major version of MarkLogic.  Bonus points if this can be done using Travis CI's matrix feature where we only need to manage a MarkLogic version property and the build script would "do the right thing."

**Comment by rjrudin** [comment]
This is handled internally via Jenkins now.
